package me.siyum.schola.dao;

public enum DAOTypes {
    STUDENT, CLASS, PARENT, TASKS, EMPLOYEE, ANNOUNCEMENT, EXAMS, EXAM_QUESTIONS, SUBJECTS, CLASS_ROOMS, CLASSES, BATCHES,
    SALARY, STUDENT_MARK, ATTENDANCE, ATTENDANCE_MARK, HOME_WORK, HOME_WORK_STUDENT, LECTURER_VOTE, LECTURER_SCHOLA, NOTIFICATION,
    NOTIFICATION_STUDENT, FEE
}
