package me.siyum.schola.util;

public enum Routes {
    RECEPTIONIST, RECEPTIONIST_STUDENTS, RECEPTIONIST_SALARY, ADMIN_STUDENTS, ADMIN, ADMIN_EMPLOYEE,
    ADMIN_HOME, ADMIN_ANOUNCEMENTS, ADMIN_INCOME, ADMIN_SETTINGS, SECRETARY_HOME, SECRETARY_APPROVAL,
    SECRETARY_PAYMENTS, SECRETARY_CLASSES, SECRETARY_STUDENTS, LECTURER_DASHBOARD, LECTURER_EXAM, LECTURER_STUDENTS,
    LECTURER_REPORTS, LECTURER_CLASS, LECTURER_SALARY, LECTURER_ATTENDANCE, STUDENT_ANNOUNCEMENT, STUDENT_EXAMS,
    STUDENT_DASHBOARD, STUDENT_CLASSES, LOGIN, SECRETARY, LECTURER, STUDENT, RECEPTIONIST_HOME, RECEPTIONIST_ATTENDANCE
}
