package me.siyum.schola.bo;

public enum BOTypes {
    STUDENT, CLASS, PARENT, TASKS, EMPLOYEE, ANNOUNCEMENTS, EXAMS, EXAM_QUESTIONS, SUBJECTS, CLASS_ROOMS, CLASSES, BATCHES,
    SALARY, STUDENT_MARK, ATTENDANCE, ATTENDANCE_MARK, HOME_WORK, HOME_WORK_STUDENT, LECTURER_VOTE, LECTURER_SCHOLA, NOTIFICATION,
    NOTIFICATION_STUDENT, FEE, USERS, ATTENDANCE_MARKING, CLASS_SCHEDULER, EXAM_RESULT, SAVE_STUDENTS
}
